# Praktikum Kecerdasan Buatan - Post-Test 4: Preprocessing Data

#### Nama: Hangberki Visnu Go
#### NIM: 2009106088

# Import Library dan Read Data
Import library.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("music_genre.csv")
df.head(5)

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
0,32894.0,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,0.115,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic
1,46652.0,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,0.124,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic
2,30097.0,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,0.534,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic
3,62177.0,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,0.157,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic
4,24907.0,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,0.157,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic

# Data Splitting
Melakukan subset target dan feature

In [5]:
X = df.iloc[:,:-1] # Target
y = df.iloc[:,-1] # Feature

Buat pembagian train_test_split dengan perbandinga 70:30. Parameter test_size yang mengatur berapa besar pembagian diberi nilai 0.3 karena 0.3 sama dengan 30%

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Menampilkan dimensi hasil splitting

In [8]:
print("Dimensi data\t:", df.shape)
print()
print("Dimensi X_train\t:", X_train.shape)
print("Dimensi X_test\t:", X_test.shape)
print("Dimensi y_train\t:", y_train.shape)
print("Dimensi y_test\t:", y_test.shape)

Dimensi data	: (50005, 18)

Dimensi X_train	: (35003, 17)
Dimensi X_test	: (15002, 17)
Dimensi y_train	: (35003,)
Dimensi y_test	: (15002,)

Normalisasi Data: Min-Max Scaler
Import library untuk MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

Membuat kelas MinMaxScaler ke variabel min_max_scaler.

In [10]:
min_max_scaler = MinMaxScaler()

Menduplikat DataFrame df ke to_be_normalized, kemudian menampilkan kolom-kolomnya.

In [12]:
to_be_normalized = df.copy()
to_be_normalized.columns

Index(['instance_id', 'artist_name', 'track_name', 'popularity',
       'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'obtained_date', 'valence', 'music_genre'],
      dtype='object')

Melakukan proses normalisasi data pada kolom "loudness", "duration_ms", "energy"

In [16]:
x_scaler = min_max_scaler.fit_transform(to_be_normalized[["loudness", "duration_ms", "energy"]])

Mengonversi hasil normalisasi menjadi DataFrame

In [17]:
df_normalized = pd.DataFrame(x_scaler)
df_normalized

              0         1         2
0      0.823883  0.000000  0.941896
1      0.787616  0.045190  0.890804
2      0.835381  0.044635  0.755562
3      0.837724  0.034546  0.700463
4      0.802914  0.046034  0.587260
...         ...       ...       ...
50000  0.788029  0.000000  0.574237
50001  0.733058  0.052139  0.361856
50002  0.819118  0.039226  0.763576
50003  0.827525  0.054398  0.472054
50004  0.657492  0.055328  0.642359

[50005 rows x 3 columns]

Menampilkan nilai min dan max dari DataFrame hasil normalisasi untuk membuktikan bahwa normalisasi dieksekusi dengan benar. Hasil normalisasi memiliki rentang [0, 1].

In [18]:
print("Nilai min:")
print(df_normalized.min())
print()
print("Nilai max:")
print(df_normalized.max())

Nilai min:
0    0.0
1    0.0
2    0.0
dtype: float64

Nilai max:
0    1.0
1    1.0
2    1.0
dtype: float64

# Standardisasi Data
Import library.
Membuat kelas StandardScaler ke variabel std_scaler.

In [21]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [23]:
to_be_standardized = df.copy()
standardized_data = std_scaler.fit_transform(to_be_standardized[["loudness", "duration_ms", "energy"]])
print("Nilai standar deviasi setelah scaling:", np.nanstd(standardized_data))

Nilai standar deviasi setelah scaling: 0.9999999999999999

In [24]:
df_standardized = pd.DataFrame(standardized_data)
df_standardized

              0         1         2
0      0.638132 -1.719534  1.289876
1      0.339248 -0.023001  1.097101
2      0.732892 -0.043830  0.586813
3      0.752201 -0.422611  0.378918
4      0.465324  0.008676 -0.048212
...         ...       ...       ...
50000  0.342655 -1.719534 -0.097351
50001 -0.110376  0.237874 -0.898692
50002  0.598865 -0.246906  0.617052
50003  0.668150  0.322687 -0.482901
50004 -0.733132  0.357614  0.159683

[50005 rows x 3 columns]

 # Data Cleaning: null

In [25]:
from sklearn.impute import SimpleImputer

In [26]:
imputer_mean = SimpleImputer(strategy="mean")
imputer_most_frequent = SimpleImputer(strategy="most_frequent")

In [27]:
df.isna().sum()

instance_id         5
artist_name         5
track_name          5
popularity          5
acousticness        5
danceability        5
duration_ms         5
energy              5
instrumentalness    5
key                 5
liveness            5
loudness            5
mode                5
speechiness         5
tempo               5
obtained_date       5
valence             5
music_genre         5
dtype: int64

In [37]:
df["instance_id"] = imputer_mean.fit_transform(df[["instance_id"]])
df["track_name"] = imputer_most_frequent.fit_transform(df[["track_name"]])
df["popularity"] = imputer_most_frequent.fit_transform(df[["popularity"]])
df["acousticness"] = imputer_most_frequent.fit_transform(df[["acousticness"]])
df["danceability"] = imputer_most_frequent.fit_transform(df[["danceability"]])
df["duration_ms"] = imputer_mean.fit_transform(df[["duration_ms"]])
df["energy"] = imputer_most_frequent.fit_transform(df[["energy"]])
df["instrumentalness"] = imputer_most_frequent.fit_transform(df[["instrumentalness"]])
df["key"] = imputer_most_frequent.fit_transform(df[["key"]])
df["liveness"] = imputer_most_frequent.fit_transform(df[["liveness"]])
df["loudness"] = imputer_most_frequent.fit_transform(df[["loudness"]])
df["speechiness"] = imputer_most_frequent.fit_transform(df[["speechiness"]])
df["tempo"] = imputer_most_frequent.fit_transform(df[["tempo"]])
df["obtained_date"] = imputer_most_frequent.fit_transform(df[["obtained_date"]])

In [38]:
df.isna().sum()

instance_id         0
artist_name         5
track_name          0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                5
speechiness         0
tempo               0
obtained_date       0
valence             5
music_genre         5
dtype: int64

# Data Cleaning: Duplicated

In [39]:
df.duplicated().sum()

4

In [40]:
df[df.duplicated()]

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
10001,55888.39636,NaN,Home,52.0,0.995,0.529,221252.60286,0.675,0.0,G,0.11,-5.443,NaN,0.0332,?,4-Apr,NaN,NaN
10002,55888.39636,NaN,Home,52.0,0.995,0.529,221252.60286,0.675,0.0,G,0.11,-5.443,NaN,0.0332,?,4-Apr,NaN,NaN
10003,55888.39636,NaN,Home,52.0,0.995,0.529,221252.60286,0.675,0.0,G,0.11,-5.443,NaN,0.0332,?,4-Apr,NaN,NaN
10004,55888.39636,NaN,Home,52.0,0.995,0.529,221252.60286,0.675,0.0,G,0.11,-5.443,NaN,0.0332,?,4-Apr,NaN,NaN

In [41]:
df.drop_duplicates(inplace=True)

In [42]:
df.duplicated().sum()

0

# Mengganti Tipe Data Atribut Angka

In [43]:
df.dtypes

instance_id         float64
artist_name          object
track_name           object
popularity          float64
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo                object
obtained_date        object
valence             float64
music_genre          object
dtype: object

In [45]:
df["popularity"] = df["popularity"].astype("object")
df.dtypes

instance_id         float64
artist_name          object
track_name           object
popularity           object
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo                object
obtained_date        object
valence             float64
music_genre          object
dtype: object

# One-Hot Encoding

In [46]:
from sklearn.preprocessing import OneHotEncoder

In [47]:
encoder = OneHotEncoder(sparse=False)

In [50]:
material_enc = encoder.fit_transform(df[["mode"]])
material_enc = pd.DataFrame(material_enc)

In [51]:
df = df.join(material_enc)
df

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,...,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre,0,1,2
0,32894.0,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,...,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic,0.0,1.0,0.0
1,46652.0,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,...,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic,0.0,1.0,0.0
2,30097.0,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,...,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic,1.0,0.0,0.0
3,62177.0,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,...,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic,1.0,0.0,0.0
4,24907.0,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,...,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50000,58878.0,BEXEY,GO GETTA,59.0,0.03340,0.913,-1.0,0.574,0.00000,C#,...,-7.022,Major,0.2980,98.02799999999999,4-Apr,0.330,Hip-Hop,0.0,1.0,0.0
50001,43557.0,Roy Woods,Drama (feat. Drake),72.0,0.15700,0.709,251860.0,0.362,0.00000,B,...,-9.814,Major,0.0550,122.04299999999999,4-Apr,0.113,Hip-Hop,NaN,NaN,NaN
50002,39767.0,Berner,Lovin' Me (feat. Smiggz),51.0,0.00597,0.693,189483.0,0.763,0.00000,D,...,-5.443,Major,0.1460,131.079,4-Apr,0.395,Hip-Hop,NaN,NaN,NaN
50003,57944.0,The-Dream,Shawty Is Da Shit,65.0,0.08310,0.782,262773.0,0.472,0.00000,G,...,-5.016,Minor,0.0441,75.88600000000001,4-Apr,0.354,Hip-Hop,NaN,NaN,NaN
50004,63470.0,Naughty By Nature,Hip Hop Hooray,67.0,0.10200,0.862,267267.0,0.642,0.00000,F#,...,-13.652,Minor,0.1010,99.20100000000001,4-Apr,0.765,Hip-Hop,NaN,NaN,NaN